import type { GatsbyConfig } from 'gatsby';

export default {
  siteMetadata: {
    title: `Boilerplate Gatsby`,
    siteUrl: `https://www.yourdomain.tld`,
    titleTemplate: `%s | Boilerplate`,
    description: `Boilerplate`,
    keywords: `Boilerplate`,
    siteName: `Boilerplate`,
    author: `Boilerplate`,
    locale: `pt-BR`,
    image: {
      path: `/icons/icon-512x512.png`,
      type: `image/png`,
      size: `512`,
    },
  },
  jsxRuntime: `automatic`,
  trailingSlash: `ignore`,
  plugins: [
    `gatsby-plugin-image`,
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-sitemap`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        start_url: `/`,
        name: `Boilerplate Gatsby`,
        short_name: `Boilerplate`,
        background_color: `#00f`,
        theme_color: `#00f`,
        display: `standalone`,
        icon: `src/images/icon.png`,
        icon_options: {
          purpose: `any maskable`,
        },
      },
    },
    `gatsby-plugin-sharp`,
    `gatsby-transformer-sharp`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `./src/images/`,
      },
      __key: `images`,
    },
    {
      resolve: `gatsby-plugin-minify-html`,
      options: {
        debug: true,
        config: {
          caseSensitive: true,
          collapseBooleanAttributes: true,
          collapseInlineTagWhitespace: true,
          collapseWhitespace: true,
          conservativeCollapse: true,
          continueOnParseError: true,
          decodeEntities: true,
          html5: true,
          minifyCSS: true,
          minifyJS: true,
          minifyURLs: true,
          preventAttributesEscaping: true,
          removeComments: true,
          removeEmptyAttributes: true,
          removeRedundantAttributes: true,
          removeScriptTypeAttributes: true,
          removeStyleLinkTypeAttributes: true,
          removeTagWhitespace: true,
          trimCustomFragments: true,
          useShortDoctype: true,
        },
      },
    },
    `gatsby-plugin-offline`,
  ],
} as GatsbyConfig;
