module.exports = {
  screens: '{breakpoints}',
  colors: '{color}',
  columns: '{sizing}',
  spacing: '{spacing}',
  animation: '{animation.declaration}',
  borderColor: '{color}',
  borderRadius: '{border.radius}',
  borderWidth: '{border.width}',
  boxShadow: '{shadow.box}',
  boxShadowColor: '{color}',
  caretColor: '{color}',
  accentColor: '{color}',
  divideColor: '{color}',
  divideWidth: '{border.width}',
  dropShadow: '{shadow.drop}',
  fill: '{color}',
  fontFamily: {
    mono: [
      '{font.family.mono.400.Fira_Code}',
      'ui-monospace',
      'SFMono-Regular',
      'Menlo',
      'Monaco',
      'Consolas',
      '"Liberation Mono"',
      '"Courier New"',
      'monospace',
    ],
  },
  fontSize: '{font.size}',
  gap: '{spacing}',
  gradientColorStops: '{color}',
  height: '{sizing}',
  inset: '{sizing}',
  keyframes: '{animation.keyframes}',
  letterSpacing: '{spacing}',
  lineHeight: '{spacing}',
  margin: '{spacing}',
  maxHeight: '{sizing}',
  maxWidth: '{sizing}',
  minHeight: '{sizing}',
  minWidth: '{sizing}',
  padding: '{spacing}',
  placeholderColor: '{color}',
  outlineColor: '{color}',
  ringColor: '{color}',
  ringOffsetColor: '{color}',
  ringOffsetWidth: '{border.width}',
  ringWidth: '{border.width}',
  rotate: '{rotate}',
  scale: '{sizing}',
  scrollMargin: '{spacing}',
  scrollPadding: '{spacing}',
  skew: '{rotate}',
  space: '{spacing}',
  stroke: '{color}',
  strokeWidth: '{border.width}',
  textColor: '{color}',
  textDecorationColor: '{color}',
  textDecorationThickness: '{border.width}',
  textIndent: '{spacing}',
  transitionDelay: '{delay}',
  transitionDuration: '{duration}',
  translate: '{spacing}',
  width: '{sizing}',
};
